### BAD Request
POST localhost:1024/api/account/hash-password
Content-Type: application/json

### OK
POST localhost:1024/api/account/hash-password
Content-Type: application/json

{
  "password": "test"
}

